### ISSUE TITLE
How do the secrets work ?

### ISSUE THREAD

**Issue by fortwoone** [kabili207/zora-sharp#18]
I am making an Oracle fangame and intend to make my game compatible with every Game and Ring Secret available in the original games, but I need to know how a secret is generated to make my game understand the passwords. Can you help me ?

**Comment by fortwoone** [comment]
Also, sorry for disturbing

**Comment by kabili207** [comment]
There is an early explanation on [GameSpot](https://gamefaqs.gamespot.com/boards/472313-the-legend-of-zelda-oracle-of-ages/66934363), but it has some inaccuracies that have been corrected over the years. Personally, I would suggest looking at the various `Load` and `ToBytes` methods for each of the secret types ([Game](https://github.com/kabili207/zora-sharp/blob/master/src/GameSecret.cs#L205), [Ring](https://github.com/kabili207/zora-sharp/blob/master/src/RingSecret.cs#L107), [Memory](https://github.com/kabili207/zora-sharp/blob/master/src/MemorySecret.cs#L130)). The encoding and cipher is handled in [`Secret.cs`](https://github.com/kabili207/zora-sharp/blob/master/src/Secret.cs).

If you're developing your game in Unity/C# you also have the option of including the zora-sharp library and letting it handle everything.

**Comment by fortwoone** [comment]
So could I try to port your code to a Python implementation since the game will be fully written in that language ?

**Comment by kabili207** [comment]
Yeah, you'll probably need to make a port of it.

@twrightsman did have a prototype python version in the works back in 2015, but it seems he's since removed it from GitHub. It is possible he might still have a copy of it laying around though.

@alexbramham also made a version for the JVM, originally in Java and later converted to Kotlin, available here: https://bitbucket.org/alexbramham/zelda-oracles-api. He uses a very different style than I do, which I would recommend having a look at as well.

**Comment by fortwoone** [comment]
I actually have the decoding system already working within the game, and you would be surprised about how it is similar to your code for ZoraSharp. There actually is a Python library that enables access to .NET namespaces and classes and makes them available to use in normal Python code, with some minor differences.
