### ISSUE TITLE
Unknown bit flags

### ISSUE THREAD

**Issue by kabili207** [kabili207/zora-sharp#5]
There are currently four unknown bit values used when creating or parsing a game secret.
- [ ] Bit 58: default 0
- [ ] Bit 59: default 0
- [x] Bit 76: default ~~1~~ 0 (flag indicating if Vasu has given you the free Friendship Ring)
- [ ] Bit 88: default 1

~~Considering 58 and 59 are located right next to each other, it's possible that they hold a 2-bit integer value (0, 1, 2, or 3). There is also the possibility that all four bits form an integer value (0 through 15).~~ Bits 58 and 59 are part of the child's behavior. What the values actually represent is still unknown.

~~As @M1CR0H4CK3R pointed out in issue #1, one or more of these values is likely used to store whether or not Maple has the vacuum cleaner.~~

**Comment by kabili207** [comment]
Spent a decent amount of time messing with the unknown values and comparing them to the offset values in a VisualBoyAdvance save file. I already knew where to look for other values based on previous work with VBA save files, so this was actually rather helpful.

Assuming slot zero, this is where each unknown value stored in the save file by the games:

Secret Bit | Save Offset | Special Instructions
------------ | --------------- | -------------------------
 Bit 58 | 111 | `value >> 4 & 1`
 Bit 59 | 111 | `value >> 5 & 1`
 Child's behavior | 111 | `value & 15`
 bit 88 | 112 | `value >> 3 & 1`
 Animal friend | 112 | `value & 7`
 Bit 76 | 117 |

I've included the behavior and animal because they happen to be stored at offset 111 and 112 respectively. I don't believe this to be simple coincidence either. Values such as the flags for a Linked Game or Hero's quest each get a whole byte (8 bits) for storage when they only need a single bit.

While I haven't actually played any of the save files I've created, based on what I've seen in the save files, I've come to the following conclusions:
 * Bits 58 and 59 are related to the child's behavior in some way
 * Bit 76 is probably for Maple's ride
 * Bit 88 is related to the animal friend

Here are the secrets I used to make my save files. All of them should be used in Ages.

 Bit set | Secret
 --------- | --------
none | `h(*6↑ wWw!h m+T7( )DR♦↓`
 58 | `h(*6↑ wWw!f m+T7( )DR♦→`
 59 | `h(*6↑ wWw!j m+T7( )DR♦@`
 76 | `h(*6↑ wWw!h m+Y7( )DR♦→`
 88 | `h(*6↑ wWw!h m+T7) )DR♦→`

If I'm right, the secret for bit 76 should be the only one where Maple has the vacuum cleaner.

**Comment by M1CR0H4CK3R** [comment]
Maybe Bit 88 is for whether the flute was bought, won, or given? I think that if it was bought, you need to buy it in a Linked Game before you can do the Nuun Highlands event (Ages) or the Spool Swamp sequence (Seasons) (I'm not 100% sure about this). Also, for Bits 58 and 59, see if you can find some similarities using this [FAQ](http://db.gamefaqs.com/portable/gbcolor/file/zelda_oracles_bipins_son.txt). I'll try to upload some VBA-M R1229 savestates in the future, each one utilizing different ways of acquiring the flutes, and each one at the endgame linked game password screen.

**Comment by kabili207** [comment]
I started playing with the "none" secret to see if I could verify where the rings are stored at in the save file (offset 118) and I noticed something rather unexpected. Simply talking with Vasu seems to set offset 117 to 1. I can't fathom why this value would be used in the secrets.

**Comment by kabili207** [comment]
I've figured out what bit 76 is for. It appears to be a flag used to tell if Vasu has given you the free Friendship Ring or not. When I loading the game created with this flag already set, he only gave me the Ring box.

**Comment by kabili207** [comment]
Bits 58 and 59 is definitely related to the child's behavior. Flipping bit 58 from 0 to 1 changed him from being curious/bouncy to hyperactive.

**Comment by LunarCookies** [comment]
I haven't seen any link between passwords and maple in any way.She'll be flying on vacuum on new games and on ufo on linked ones after the seventh encounter or so.

**Comment by kabili207** [comment]
I'm going to have to agree with you @LunarCookies, there's just nowhere left in the secrets where information on Maple can be stored.

I get the feeling that bits 58 and 59 are used for the higher values that are possible for the child, with the lower four bits we already knew about being used to represent all values possible in the first game and the upper two bits used for the remaining values in the second game. This ups the number of possible values from 16 to 64, which is decidedly harder to test with any kind of certainty. We still don't really know what the original 16 values actually represent to begin with.

**Comment by alexbramham** [comment]
I think bit 88 relates to whether the flute was received or not, though since the game forces you to choose an animal friend it will always be set. I'm interested to see what would happen if this value were set 0.

I think the six bits all relate to the child's personality though only the first 4 can be controlled in the first game. Is it possible that in the forth game in a sequence the game remembers your answers to the grown child in the second and you don't get to answer the grown child's questions hence get the same reward?

I've updated my java implementation with the interpretation of the Vasu ring, great discovery!

**Comment by Drenn1** [comment]
I'm a few years too late to this party, but I'm working on a disassembly for ages/seasons, and I wanted to shed some light on the unknown bits.

In my disassembly, I found the structure that tells the game how to encode each bit, and it looks like this:

```
	                            ; Bit number:
	.db <wFileIsHeroGame	$01 ; 20
	.db <wWhichGame		$01 ; 21
	.db <wLinkName		$08 ; 22
	.db <wKidName		$08 ; 30
	.db <wLinkName+1	$08 ; 38
	.db <wKidName+1		$08 ; 46
	.db <wChildBehaviour	$06 ; 54
	.db <wLinkName+2	$08 ; 60
	.db <wKidName+2		$08 ; 68
	.db <wObtainedRingBox	$01 ; 76
	.db <wLinkName+3	$08 ; 77
	.db <wAnimalRegion	$04 ; 85
	.db <wLinkName+4	$08 ; 89
	.db <wKidName+3		$08 ; 97
	.db <wFileIsLinkedGame	$01 ; 105
	.db <wKidName+4		$08 ; 106
	.db <wLinkName+5	$02 ; 108 (This is always 00)
```

The way you interpret this is: the second column is the variable to encode, and the third column is the number of bits required to encode that variable. (I put the bit numbers in comments to help follow along. I skipped the "header" which consists of the GameID, secret type, and xor cipher.)

The animal region uses 4 bits. That may seem strange, since technically it could fit in 2, but the developers decided to make numbers 0x0b, 0x0c, and 0x0d correspond to ricky, dimitri, and moosh. They need 4 bits to encode numbers that high. They seem to have done it this way so that the numbers are consistent with their "object IDs", but that's not really important. Anyway, bits 85-88 are all used for the animal region.

And, as you suspected, bits 54-59 are all part of the child's behaviour. I don't know the valid values yet, though.

So, the only thing you're missing is a more complete list of possible values for the child's behaviour. I'll get back to you when I have a better understanding of that.

**Comment by alexbramham** [comment]
Hi

Thanks for letting me know about this, great research!

Alex

On 20 Dec 2017, at 02:47, Drenn1 <notifications@github.com> wrote:

I'm a few years too late to this party, but I'm working on a disassembly for ages/seasons, and I wanted to shed some light on the unknown bits.

In my disassembly, I found the structure that tells the game how to encode each bit, and it looks like this:

	                            ; Bit number:
	.db <wFileIsHeroGame	$01 ; 20
	.db <wWhichGame		$01 ; 21
	.db <wLinkName		$08 ; 22
	.db <wKidName		$08 ; 30
	.db <wLinkName+1	$08 ; 38
	.db <wKidName+1		$08 ; 46
	.db <wChildBehaviour	$06 ; 54
	.db <wLinkName+2	$08 ; 60
	.db <wKidName+2		$08 ; 68
	.db <wObtainedRingBox	$01 ; 76
	.db <wLinkName+3	$08 ; 77
	.db <wAnimalRegion	$04 ; 85
	.db <wLinkName+4	$08 ; 89
	.db <wKidName+3		$08 ; 97
	.db <wFileIsLinkedGame	$01 ; 105
	.db <wKidName+4		$08 ; 106
	.db <wLinkName+5	$02 ; 108 (This is always 00)
The way you interpret this is: the second column is the variable to encode, and the third column is the number of bits required to encode that variable. (I put the bit numbers in comments to help follow along. I skipped the "header" which consists of the GameID, secret type, and xor cipher.)

The animal region uses 4 bits. That may seem strange, since technically it could fit in 2, but the developers decided to make numbers 0x0b, 0x0c, and 0x0d correspond to ricky, dimitri, and moosh. They need 4 bits to encode numbers that high. They seem to have done it this way so that the numbers are consistent with their "object IDs", but that's not really important. Anyway, bits 85-88 are all used for the animal region.

And, as you suspected, bits 54-59 are all part of the child's behaviour. I don't know the valid values yet, though.

So, the only thing you're missing is a more complete list of possible values for the child's behaviour. I'll get back to you when I have a better understanding of that.

**Comment by Drenn1** [comment]
So, I've analyzed the child behaviour: http://wiki.zeldahacking.net/oracle/Bipin_and_Blossom%27s_son

I'm now calling bits 54-59 the child's "status". This is a counter which gets increased by various values depending on your responses to Blossom's questions. The child's personality is decided depending on what range this falls under.

For values 1-5, he's curious; 6-10, he's shy; 11+, he's hyperactive.

That's not the end of it, though, since this also affects his second personality. See the linked page for more details.

As an example, if you set the status to the maximum value of 63 (since it takes 6 bits in the password), the child would be locked into becoming hyperactive, then an arborist. There's nothing you can do to change that since you can't decrease the status.

It may be more accurate to replace the enum with a byte value, though that would be less intuitive. I'm not sure what should be done, but here are a few more observations:

* According to my calculations, the maximum value it can be in an unlinked game is 21. Across both games, the maximum is 33.
* In hero secrets, I believe this value is still encoded into the secret, even though it will be reset to zero by the game. With the current enum, this may cause discrepencies when you tell ZoraSharp to decode, then re-encode a secret.

**Comment by kabili207** [comment]
I'd argue that the enum isnt intuitive either since it's not really clear what the difference between BouncyC and BouncyD are. A byte is a far more accurate representation  and it's relatively easy to update the UIs without losing the textual values. I'll just have to hide the labels or something when selecting a Hero secret since there's no way to know what the second personality is with just the counter.

Thanks for everything you've done!

**Comment by kabili207** [comment]
The library has been updated to account for all previously unknown values, so I'm going to close this ticket. Both the GTK and WPF interfaces will be updated to use this updated version shortly.
